### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by bakercp** [JoachimSchurig/CppGPIO#1]
This isn't an issue, just a thank you as Github doesn't offer a super easy way to say thanks besides stars.

I just wrapped up CppGPIO for openFrameworks with great success.  Looking forward to using it.  There are a few other options available for openFrameworks (https://github.com/joshuajnoble/ofxWiringPi and https://github.com/kashimAstro/ofxGPIO), but they use wiring pi and sysfs.  I was very happy to find your implementation!

Anyway, thanks!

**Comment by bakercp** [comment]
And, obviously feel free to close this "issue". :+1:

**Comment by bakercp** [comment]
Ah, one other thing.  The ability to compile and "test" code on Xcode / OSX and then take it over to the Raspberry Pi is a really nice feature.  +1 for "simulator" mode.

**Comment by JoachimSchurig** [comment]
You're welcome! I did not notice the ofx project until your comment - looks very interesting indeed! Good to know that you could make use of CppGPIO for it. 
Cheers,
Joachim

**Comment by bakercp** [comment]
Thx!
