### ISSUE TITLE
Undefined reference when compiling example code 

### ISSUE THREAD

**Issue by marcs7** [JoachimSchurig/CppGPIO#11]
When compiling the example code 

```
#include <chrono>
#include <cppgpio.hpp>
int main()
{
	// use gpio #18

	GPIO::DigitalOut out(18);

	 //switch output to logical 1 (3.3V)

	out.on();

	// wait some time

	std::this_thread::sleep_for(std::chrono::milliseconds(1));

	// switch it off again

	out.off();

	return 0;
}
```

the following error appear 

```
Error		undefined reference to `GPIO::DigitalOut::DigitalOut(unsigned int)'	
```

How can I solve it?

**Comment by JoachimSchurig** [comment]
you either need to `sudo make install` the library first before compiling the sample, or tell the linker where to find it with `-L`, and in both cases use `-lcppgpio` to tell the linker to use the library

**Comment by marcs7** [comment]
I've installed the library and added the `-lcppgpio` and a new error comes up
 ```Error		/usr/lib/gcc/aarch64-linux-gnu/9/../../../../lib/libcppgpio.so: undefined reference to `pthread_create'```	
Solved added `pthread` to linker option in viusal studio

Close issue
