### ISSUE TITLE
Unable to switch GPIO pin to high (1) in simulation mode

### ISSUE THREAD

**Issue by alkavan** [JoachimSchurig/CppGPIO#13]
Should this even work? Or am I missing something?

Consider the following code:

```
GPIO::GPIOBase::simulation(true);
GPIO::DigitalOut out(11);
out.on();
std::this_thread::sleep_for(std::chrono::milliseconds(1));
```

I did expect the value of `gpio_addr` turn to `1` but this does not happen.

**Comment by JoachimSchurig** [comment]
no, this is not expected to change any internal state. Simulation mode does - nothing..
