### ISSUE TITLE
licens? and my changes to this library

### ISSUE THREAD

**Issue by MariwanJ** [JoachimSchurig/CppGPIO#14]
Hi, 
I found your library useful but I also found many bugs that I needed to target. 
I would make PR if you merge it to the main but if you are not able to do so I keep My version. 
I couldn't see any Licens. Kindly would you choose one? 
Let me know if you wish to get the RP.
Thanks for the library 
Mariwan

**Comment by JoachimSchurig** [comment]
Hello Mariwan,

As stated in the readme, the license is BSD (whichever version).

If you want to contribute, please create one PR per issue, so that we can discuss them separately.

Thank you,
Joachim

**Comment by MariwanJ** [comment]
Why BSD? It means your library is not allowed to be used in commercial? Am I wrong?
If so, I wouldn't contribute to the library. 
I sent you the PR .. if BSD disallow using the library in commercial .. I wouldn't help in developing and I am sorry.
