### ISSUE TITLE
how can I activate simulation mode in Linux?

### ISSUE THREAD

**Issue by ghost** [JoachimSchurig/CppGPIO#4]
hello Joachim Schurig,

Can you tell me how can I force GPIO into simulation mode when working on a Linux host OS?

thank you.

**Comment by JoachimSchurig** [comment]
Hi Markus,

to enter simulation mode on Linux you have to call 

GPIO::GPIOBase::simulation(true)

once before accessing any methods of the GPIO classes.

From gpio.hpp:


        /// Set "simulation" mode - that is, no real IO, but instead dummy operating
        /// only. Simulation mode is set automatically when this code is run on OS
        /// other than Linux, but if you want to run in this mode on Linux you
        /// have to call simulation(true) explicitly.

        static void simulation(bool yes);

        /// returns true if simulation (dummy) mode is set

        static bool simulation() { return simulate; }

Best regards,
Joachim

**Comment by ghost** [comment]
ok, I see now. It is working now :)

thank you
