### ISSUE TITLE
Hardware PWM 

### ISSUE THREAD

**Issue by starrabb1t** [JoachimSchurig/CppGPIO#5]
Board: RPi 3
OS: Raspbian Stretch

How to run hardware generated PWM? I tried all pins, but _is_software_emulation()_ always returns '1'.

**Comment by starrabb1t** [comment]
Aha, sorry for the issue.
Just understood, that it works with bcm2835, not with bcm2837. 

I guess I need to look through registers in gpio.cpp/gpio.h to make it compatible with RPi 3. Am I right?

**Comment by dipampatel18** [comment]
@starrabb1t Could you find a way to use it for BCM2837? I'm trying to use it for RPi 4 which is BCM2711.
