### ISSUE TITLE
How to be ported to other boards

### ISSUE THREAD

**Issue by how0723** [JoachimSchurig/CppGPIO#8]
How to be ported to other boards

**Comment by JoachimSchurig** [comment]
See this comment in gpio.h:
    /// This is the implementation of a concrete GPIO control, the one in the BCM2835.
    /// This is a temporary solution which will get replaced by a factory model
    /// to choose from different GPIOs, with the below public functionality being
    /// the factory abstract base.
I never implemented that factory model because I did in fact never use different hardware than the raspberry with this library.
But that is the path forward to porting it.
